
[Client]
	#The side for information rendered on the HUD. Ex: LEFT, RIGHT
	overlaySide = "LEFT"
	#Displays Nature's Compass information even while chat is open.
	displayWithChatOpen = true
	#Fixes biome names by adding missing spaces. Ex: ForestHills becomes Forest Hills
	fixBiomeNames = true
	#The line offset for information rendered on the HUD.
	overlayLineOffset = 1

