
#Settings for the salvager
[salvager]

	[salvager.partLossRate]
		#Minimum rate of part loss when salvaging items. 0 = no loss, 1 = complete loss.
		#Rate depends on remaining durability.
		min = 0.0
		#Maximum rate of part loss when salvaging items. 0 = no loss, 1 = complete loss.
		#Rate depends on remaining durability.
		max = 0.5

[item]

	#Blueprint and template settings
	[item.blueprint]
		#Allowed blueprint types. Valid values are: BOTH, BLUEPRINT, and TEMPLATE
		typesAllowed = "BOTH"
		#When joining a new world, should players be given a blueprint package?
		#The blueprint package gives some blueprints when used (right-click).
		#To change what is given, override the starter_blueprints loot table.
		spawnWithStarterBlueprints = true

	#Silent Gear allows some items to be used to place blocks.
	#You can change which items place blocks and what other items they can activate.
	[item.blockPlacers]
		#These items are able to place blocks. The player must be sneaking.
		placerTools = ["silentgear:axe", "silentgear:pickaxe", "silentgear:shovel"]
		#These items can be used by placer tools. The player must be sneaking.
		#Note that some items may not work with this feature.
		placeableItems = ["danknull:dank_null", "torchbandolier:torch_bandolier", "xreliquary:sojourner_staff"]

	#Settings for sinew drops
	[item.sinew]
		#These entities can drop sinew when killed.
		dropsFrom = ["minecraft:cow", "minecraft:pig", "minecraft:sheep"]
		#Drop rate of sinew (chance out of 1)
		dropRate = 0.2

	#Settings for gear (tools, weapons, and armor)
	[item.gear]
		#If true, gear breaks permanently, like vanilla tools and armor
		breaksPermanently = false

		[item.gear.repairs]
			#Effectiveness of quick gear repairs (crafting grid). Set to 0 to disable quick repairs.
			quickEffectiveness = 0.35
			#Effectiveness of gear repairs done in an anvil. Set to 0 to disable anvil repairs.
			anvilEffectiveness = 0.5

		#Settings for AOE tools (hammer, excavator)
		#Match modes determine what blocks are considered similar enough to be mined together.
		#LOOSE: Break anything (you probably do not want this)
		#MODERATE: Break anything with the same harvest level
		#STRICT: Break only the exact same block
		[item.gear.aoeTools]

			[item.gear.aoeTools.matchMode]
				#Match mode for most blocks
				standard = "MODERATE"
				#Match mode for ore blocks (anything in the forge:ores block tag)
				ores = "STRICT"

		[item.gear.upgrades]
			#If true, upgrade parts may only be applied in an anvil.
			applyInAnvilOnly = false

