
#Simple Sponge Config
[sponge]
	#Set the range for a Sponge
	spongeRange = 3
	#Set the durability for a Sponge On A Stick
	spongeOnAStickMaxDamage = 256
	#Set the range for a Sponge On A Stick
	spongeOnAStickRange = 3

[magmatic_sponge]
	#Set the durability for a Magmatic Sponge On A Stick
	magmaticSpongeOnAStickMaxDamage = 256
	#Set the range for a Magmatic Sponge On A Stick
	magmaticSpongeOnAStickRange = 3
	#Set the range for a Magmatic Sponge
	magmaticSpongeRange = 3

[compressed_sponge]
	#Set the durability (multiplied by 9) for a Compressed Sponge On A Stick
	compressedSpongeOnAStickMaxDamage = 256
	#Set the range (multiplied by 2) for a Compressed Sponge On A Stick
	compressedSpongeOnAStickRange = 3
	#Set the range (multiplied by 2) for a Compressed Magmatic Sponge On A Stick
	compressedMagmaticSpongeOnAStickRange = 3
	#Set the durability (multiplied by 9) for a Compressed Magmatic Sponge On A Stick
	compressedMagmaticSpongeOnAStickMaxDamage = 256

[energized_sponge]
	#Set to true to enable the Energized Sponge On A Stick (Requires Redstone Flux to be installed)
	enableEnergizedSpongeOnAStick = true
	#Set the range for an Energized Sponge On A Stick
	energizedSpongeOnAStickRange = 7
	#Set the per right click energy use for an Energized Sponge On A Stick
	energizedSpongeOnAStickPerRightClickUse = 100
	#Set the max energy for an Energized Sponge On A Stick
	energizedSpongeOnAStickMaxEnergy = 500000

[misc]
	#When OpenBlocks is detected, certain crafting recipes will be changed / disabled.
	#Set this to false if you wish to use the sponges from this mod.
	#You'll have to use CraftTweaker to prevent recipe conflicts.
	openBlocksIntegration = true

